name: CongregationKit

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: '*'

jobs:
  ubuntu_test:
    name: Ubuntu Build
    runs-on: ubuntu-22.04
    container: swift:6.0-jammy
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
  macos_test:
    name: macOS Build
    runs-on: macos-15
    steps:
    - name: Select appropriate Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
  format:
    name: Lint Formatting
    runs-on: ubuntu-22.04
    container: swift:6.0-jammy
    steps:
    - uses: actions/checkout@v4
    - name: Lint
      run: swift format lint --strict --recursive .